//go:build arm64 && go1.27

package int8dot

// NEON widening multiply-accumulate kernels for arm64, generated by go-asmgen
// (kernels_arm64_gen.go) into kernels_arm64.s.
//
// These need the integer NEON widening multiply (VSMULL/VUMULL) and the
// VSXTL/VUXTL byte→halfword widening, which the Go arm64 assembler only gained in
// Go 1.27 (the released assembler exposes only the polynomial VPMULL). The build
// is therefore guarded //go:build arm64 && go1.27; on stable Go the generic build
// (dispatch_generic.go) falls back to the scalar reference. NEON is the arm64
// baseline, so there is no runtime feature gate.
//
// NOTE on SDOT/UDOT: AArch64's dedicated byte dot-product instructions are
// exposed by the Go 1.27 assembler only in their SVE form (ZSDOT/ZUDOT/ZUSDOT,
// Z-registers + predicate), which go-asmgen does not model and which Apple
// Silicon does not implement; the widening-multiply path used here is the
// portable NEON kernel that runs and is validated on every arm64 host.

func dotNEON(a, b []int8) int32
func dotUint8NEON(a, b []uint8) uint32
func dotU8S8NEON(a []uint8, b []int8) int32

func dot(a, b []int8) int32             { return dotNEON(a, b) }
func dotUint8(a, b []uint8) uint32      { return dotUint8NEON(a, b) }
func dotU8S8(a []uint8, b []int8) int32 { return dotU8S8NEON(a, b) }
