//go:build loong64

package int8dot

// LSX even/odd widening multiply-accumulate kernels, generated by go-asmgen
// (kernels_loong64_gen.go) into kernels_loong64.s. LSX is the LA464 baseline, so
// there is no runtime feature gate.
//
// DotU8S8 stays on the scalar reference: LoongArch has no mixed unsigned×signed
// byte multiply.

func dotLSX(a, b []int8) int32
func dotUint8LSX(a, b []uint8) uint32

func dot(a, b []int8) int32        { return dotLSX(a, b) }
func dotUint8(a, b []uint8) uint32 { return dotUint8LSX(a, b) }
func dotU8S8(a []uint8, b []int8) int32 {
	return dotU8S8Ref(a, b)
}
