//go:build riscv64

package int8dot

import "golang.org/x/sys/cpu"

// RVV widening multiply-accumulate kernels, generated by go-asmgen
// (kernels_riscv64_gen.go) into kernels_riscv64.s. Gated at runtime on
// cpu.RISCV64.HasV (RVV 1.0); without the vector extension the scalar reference
// is used.

func dotRVV(a, b []int8) int32
func dotUint8RVV(a, b []uint8) uint32
func dotU8S8RVV(a []uint8, b []int8) int32

var hasV = cpu.RISCV64.HasV

func dot(a, b []int8) int32 {
	if hasV {
		return dotRVV(a, b)
	}
	return dotRef(a, b)
}

func dotUint8(a, b []uint8) uint32 {
	if hasV {
		return dotUint8RVV(a, b)
	}
	return dotUint8Ref(a, b)
}

func dotU8S8(a []uint8, b []int8) int32 {
	if hasV {
		return dotU8S8RVV(a, b)
	}
	return dotU8S8Ref(a, b)
}
