//go:build s390x

package int8dot

// z/Architecture vector-facility even/odd widening multiply-accumulate kernels,
// generated by go-asmgen (kernels_s390x_gen.go) into kernels_s390x.s. The vector
// facility is the z13 baseline, so there is no runtime feature gate.
//
// DotU8S8 stays on the scalar reference: z has no mixed unsigned×signed byte
// multiply.

func dotVX(a, b []int8) int32
func dotUint8VX(a, b []uint8) uint32

func dot(a, b []int8) int32        { return dotVX(a, b) }
func dotUint8(a, b []uint8) uint32 { return dotUint8VX(a, b) }
func dotU8S8(a []uint8, b []int8) int32 {
	return dotU8S8Ref(a, b)
}
