//go:build ppc64le

package int8dot

import "golang.org/x/sys/cpu"

// VMX even/odd widening multiply-accumulate kernels, generated by go-asmgen
// (kernels_ppc64le_gen.go) into kernels_ppc64le.s. The kernels emit ISA-3.0
// (POWER9) instructions (e.g. LXVB16X), which raise SIGILL on POWER8, so they
// run only when hasVSX reports POWER9+; on POWER8 the scalar reference
// (reference.go) does the work.
//
// DotU8S8 stays on the scalar reference: Power has no mixed unsigned×signed byte
// multiply, and synthesising one would cost more than the scalar loop.

func dotVMX(a, b []int8) int32
func dotUint8VMX(a, b []uint8) uint32

// hasVSX gates the generated kernels. They use ISA-3.0 (POWER9) instructions
// (e.g. LXVB16X) that are illegal on POWER8, so the kernels run only on
// POWER9+; otherwise the scalar reference is used. It is a var (not a const) so
// the dispatch test can also drive the fallback.
var hasVSX = cpu.PPC64.IsPOWER9

func dot(a, b []int8) int32 {
	if hasVSX {
		return dotVMX(a, b)
	}
	return dotRef(a, b)
}

func dotUint8(a, b []uint8) uint32 {
	if hasVSX {
		return dotUint8VMX(a, b)
	}
	return dotUint8Ref(a, b)
}

func dotU8S8(a []uint8, b []int8) int32 {
	return dotU8S8Ref(a, b)
}
