//go:build amd64

package int8dot

import "golang.org/x/sys/cpu"

// AVX2 integer multiply-accumulate kernels, generated by go-asmgen
// (kernels_amd64_gen.go) into kernels_amd64.s. Each uses the byte→word→int32
// VPMADDWD path. Gated at runtime on cpu.X86.HasAVX2; without it the scalar
// reference is used.
//
// AVX-512-VNNI (VPDPBUSD) is a natural DotU8S8 fast path but is deliberately not
// shipped here: it cannot be validated or coverage-gated in this project's
// environment (qemu TCG implements no AVX-512). See kernels_amd64_gen.go.
func dotAVX2(a, b []int8) int32
func dotUint8AVX2(a, b []uint8) uint32
func dotU8S8AVX2(a []uint8, b []int8) int32

var hasAVX2 = cpu.X86.HasAVX2

func dot(a, b []int8) int32 {
	if hasAVX2 {
		return dotAVX2(a, b)
	}
	return dotRef(a, b)
}

func dotUint8(a, b []uint8) uint32 {
	if hasAVX2 {
		return dotUint8AVX2(a, b)
	}
	return dotUint8Ref(a, b)
}

func dotU8S8(a []uint8, b []int8) int32 {
	if hasAVX2 {
		return dotU8S8AVX2(a, b)
	}
	return dotU8S8Ref(a, b)
}
