//go:build ppc64le

package int8dot

// VMX even/odd widening multiply-accumulate kernels, generated by go-asmgen
// (kernels_ppc64le_gen.go) into kernels_ppc64le.s. VSX/VMX is the POWER8
// baseline, so there is no runtime feature gate.
//
// DotU8S8 stays on the scalar reference: Power has no mixed unsigned×signed byte
// multiply, and synthesising one would cost more than the scalar loop.

func dotVMX(a, b []int8) int32
func dotUint8VMX(a, b []uint8) uint32

func dot(a, b []int8) int32        { return dotVMX(a, b) }
func dotUint8(a, b []uint8) uint32 { return dotUint8VMX(a, b) }
func dotU8S8(a []uint8, b []int8) int32 {
	return dotU8S8Ref(a, b)
}
