// Package int8dot provides SIMD-accelerated integer dot products over byte
// slices — the multiply-accumulate at the heart of quantized machine-learning
// inference, where embeddings and weights are stored as 8-bit integers to cut
// memory bandwidth and exploit per-byte vector throughput.
//
// It is pure Go (CGO_ENABLED=0, stable Go, no GOEXPERIMENT): the hot
// multiply-accumulate loops are SIMD assembly generated by go-asmgen on all six
// of Go's 64-bit SIMD targets — amd64 (AVX-512 VNNI VPDPBUSD with an
// AVX2/SSE PMADDUBSW+PMADDWD fallback), arm64 (NEON VSMULL/VUMULL widening,
// Go 1.27+; scalar on stable Go),
// ppc64le (VMX VMULESB/VMULOSB even/odd widening), s390x (vector multiply
// even/odd), riscv64 (RVV widening multiply-accumulate) and loong64 (LSX
// even/odd widening) — with a portable scalar fallback everywhere else, all on a
// plain `go build`.
//
// # Operations
//
//	Dot(a, b []int8) int32       Σ aᵢbᵢ, signed × signed
//	DotUint8(a, b []uint8) uint32 Σ aᵢbᵢ, unsigned × unsigned
//	DotU8S8(a, b []int8) int32    Σ uint8(aᵢ)·bᵢ, unsigned × signed
//
// All three require len(a) == len(b) and panic otherwise.
//
// # Saturation safety
//
// Every product of two bytes fits in 16 bits, and the sum is accumulated in a
// 32-bit (Dot, DotU8S8) or unsigned 32-bit (DotUint8) integer. With signed
// int8 inputs each product is in [-128·127, 128·128] = [-16256, 16384], so Dot
// cannot overflow int32 until roughly 131k elements of worst-case magnitude;
// DotU8S8 and DotUint8 have similar headroom. Embedding vectors (typically
// 256–4096 dims of small quantized values) stay comfortably within int32. The
// result is therefore exact — no saturation, no clamping — and the SIMD kernels
// are required to be bit-for-bit identical to the scalar reference on every
// architecture (the differential tests and FuzzDot enforce this).
//
// # DotU8S8 and the common quantization layout
//
// INT8 GEMM kernels on most hardware (x86 VNNI, ARM dot-product, etc.) multiply
// an unsigned activation byte by a signed weight byte — the u8×s8 layout —
// because a ReLU activation is naturally non-negative and is quantized to
// uint8, while weights are symmetric and quantized to int8. DotU8S8 implements
// exactly that contraction; it takes b as []int8 (the signed operand) and
// reinterprets a's bytes as uint8.
package int8dot

// Dot returns the signed integer dot product Σ aᵢbᵢ, with each int8×int8
// product widened and accumulated in int32. It panics if len(a) != len(b).
func Dot(a, b []int8) int32 {
	if len(a) != len(b) {
		panic("int8dot: slice length mismatch")
	}
	return dot(a, b)
}

// DotUint8 returns the unsigned integer dot product Σ aᵢbᵢ, with each
// uint8×uint8 product widened and accumulated in uint32. It panics if
// len(a) != len(b).
func DotUint8(a, b []uint8) uint32 {
	if len(a) != len(b) {
		panic("int8dot: slice length mismatch")
	}
	return dotUint8(a, b)
}

// DotU8S8 returns Σ uint8(aᵢ)·bᵢ — the unsigned-activation × signed-weight
// contraction used by INT8 quantized GEMM kernels. The first slice is
// reinterpreted as uint8, the second is signed int8; the int32 sum is exact.
// It panics if len(a) != len(b).
func DotU8S8(a []uint8, b []int8) int32 {
	if len(a) != len(b) {
		panic("int8dot: slice length mismatch")
	}
	return dotU8S8(a, b)
}
